### PR TITLE
This batch of changes makes the Vagrant box for OBP work again.

### PR DESCRIPTION
**Pull request by pvanisacker**
Major changes:
- Make use of Vagrant 2 syntax
- Make use of openjdk 7
- Make use of downloaded maven version 3
- Make use of Postgresql instead of H2 database
- Make use of postgresql puppet module to configure postgresql
- Clean up README

### CODE REVIEW

**Comment by Azd325** [comment]
Awesome work. Thanks Pieter

Please squash you commits a bit together

**Comment by pvanisacker** [comment]
Done

**Comment by simonredfern** [comment]
Hi Pieter,

Thanks very much for you commits!

Would you be happy to sign our contributors license agreement? 
https://github.com/OpenBankProject/OBP-VM/blob/master/Harmony_Individual_Contributor_Assignment_Agreement.txt

If so, please either sign and send to us - or better still, commit a copy of the file in a new "contributions" folder with your Name and your ("non bot readable") Email address on it.

Thanks very much.

Best,

Simon

**Comment by pvanisacker** [comment]
Simon,

I've added the contribution acknowledgement as requested.

**Pull request merged**
